[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# 🔴 FORCE all traffic to your real domain
[[redirects]]
  from = "/*"
  to = "https://addora.com.et/:splat"
  status = 301
  force = true
  conditions = {Host = ["addoraweb.netlify.app", "master--addoraweb.netlify.app"]}
